create table locations
(
    capacity    integer,
    id          integer generated by default as identity,
    address     varchar(255),
    description varchar(255),
    name        varchar(255),
    primary key (id)
)

