CREATE TABLE events
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name             VARCHAR(255),
    owner_id         INTEGER,
    max_places       INTEGER,
    occupied_places  INTEGER,
    start_at         TIMESTAMP,
    cost             INTEGER,
    duration_minutes INTEGER,
    location_id      INTEGER,
    status           VARCHAR(50)
);

CREATE TABLE registrations
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id   BIGINT    NOT NULL,
    user_id    BIGINT    NOT NULL,
    created_at TIMESTAMP NOT NULL,
    CONSTRAINT fk_registration_event
        FOREIGN KEY (event_id)
            REFERENCES events (id)
            ON DELETE RESTRICT
);