spring.application.name=online-library

spring.web.error.include-message=always
server.port=8080

spring.datasource.url=jdbc:postgresql://localhost:5431/postgres
spring.datasource.password=root
spring.datasource.username=postgres

springdoc.swagger-ui.url=/event-manager-openapi.yaml

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true