server:
  port: 8080

spring:
  application:
    name: event-manager

  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false
    show-sql: true

  data:
    redis:
      host: localhost
      port: 6379
  cache:
    type: redis

  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/changelog-master.yaml
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      properties:
        key.serializer: org.apache.kafka.common.serialization.UUIDSerializer
        value.serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      group-id: event-notificator
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"

logging:
  level:
    root: INFO
    org.springframework.web: INFO

springdoc:
  swagger-ui:
    path: /swagger-ui/index.html
    url: /event-manager-openapi.yaml

jwt:
  secretKey: Vw47liBU9qsTTOQVh26DSCMXO04XZyAQsRslmH3QlT6

event:
  status:
    cron: "0 * * * * *"

